# =========================================
# Focalboard Personal Server
# https://www.focalboard.com/download/personal-edition/docker/
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

# Configs
configs:
  focalboard-cfg:
    name: focalboard-cfg
    external: true

# Networks
networks:
  database-net:
    name: database-net
    external: true
  proxy-net:
    name: reverse-proxy
    external: true

# Volumes
volumes:
  focalboard-vol:
    name: focalboard-vol
    external: true

# Services
services:
  focalboard:
    image: mattermost/focalboard
    configs:
      - source: focalboard-cfg
        target: /opt/focalboard/config.json
        uid: "2000"
        gid: "2000"
        mode: 0440
    # # Labels for Traefik proxy
    # labels:
    #   - traefik.enable=true
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.routers.apidocs.entrypoints=websecure
    #   - traefik.http.routers.apidocs.rule=Host(`board.example.com`)
    #   - traefik.http.routers.apidocs.middlewares=internal-ips,admin-auth
    #   - traefik.http.routers.apidocs.service=focalboard
    #   - traefik.http.routers.apidocs.tls=true
    #   - traefik.http.routers.apidocs.tls.certresolver=le
    #   - traefik.http.routers.apidocs.priority=30
    #   - traefik.http.services.apidocs.loadbalancer.server.port=8000
    networks:
      - database-net
      - proxy-net
    # ports:
    #   - 8000:8000
    restart: unless-stopped
    volumes:
      - focalboard-vol:/data
