# =========================================
# Poste.io stack
#
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

volumes:
  poste-vol: {}

services:
  mail:
    image: analogic/poste.io
    hostname: mail.example.com
    container_name: mailserver
    environment:
      - TZ=Asia/Ho_Chi_Minh
    network_mode: host
    # ports:
    #   - 25      # SMTP - mostly processing incoming mails
    #   - 80      # HTTP - redirect to https (see options) and authentication for Let's encrypt service
    #   - 110     # POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth
    #   - 143     # IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
    #   - 443     # HTTPS - access to administration or webmail client
    #   - 465     # SMTPS - Legacy SMTPs port
    #   - 587     # MSA - SMTP port used primarily for email clients after STARTTLS and auth
    #   - 993     # IMAPS - alternative port for IMAP encrypted since connection
    #   - 995     # POP3S - encrypted POP3 since connections
    #   - 4190    # Sieve - remote sieve settings
    restart: unless-stopped
    volumes:
      - poste-vol:/data
