# =========================================
# Gitlab
# https://docs.gitlab.com/ee/install/docker.html
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

configs:
  gitlab-config:
    name: gitlab-config
    external: true

networks:
  database-net:
    name: database-net
    external: true
  proxy-net:
    name: reverse-proxy
    external: true

secrets:
  gitlab-root-password:
    name: gitlab-root-password
    external: true

volumes:
  gitlab-data-vol:
    name: gitlab-data-vol
    external: true
  gitlab-logs-vol:
    name: gitlab-logs-vol
    external: true
  gitlab-config-vol:
    name: gitlab-config-vol
    external: true

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    configs:
      - source: gitlab-config
        target: /gitlab.rb
    container_name: gitlab
    environment:
      - GITLAB_OMNIBUS_CONFIG=from_file('/gitlab.rb')
      - GITLAB_DOMAIN=gitlab.example.com
      - GITLAB_ROOT_PASSWORD_FILE=/run/secrets/gitlab-root-password
    # labels:
    #   # Labels for Traefik proxy
    #   - traefik.enable=true
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.routers.gitlab.entrypoints=websecure
    #   - traefik.http.routers.gitlab.rule=Host(`gitlab.example.com`)
    #   - traefik.http.routers.gitlab.service=gitlab
    #   - traefik.http.routers.gitlab.priority=30
    #   - traefik.http.services.gitlab.loadbalancer.server.port=80
    #   - traefik.tcp.routers.gitlab.entrypoints=ssh
    #   - traefik.tcp.routers.gitlab.rule=HostSNI(`gitlab.example.com`)
    #   - traefik.tcp.routers.gitlab.service=gitlab
    #   - traefik.tcp.routers.gitlab.priority=30
    #   - traefik.tcp.services.gitlab.loadbalancer.server.port=22
    networks:
      - database-net
      - proxy-net
    # ports:
    #   - 22:22
    #   - 80:80
    restart: unless-stopped
    secrets:
      - gitlab-root-password
    shm_size: 512M
    volumes:
      - gitlab-data-vol:/var/opt/gitlab
      - gitlab-logs-vol:/var/log/gitlab
      - gitlab-config-vol:/etc/gitlab
