# =========================================
# Gitlab Runner
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

configs:
  gitlab-runner-config:
    name: gitlab-runner-config
    external: true

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    configs:
      - source: gitlab-runner-config
        target: /etc/gitlab-runner/config.toml
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
