concurrent = 10
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-01"
  url = "https://gitlab.example.com"
  token = "xxxxxxxxxxxxxxxxxxxx"
  executor = "docker"
  environment = ["LC_ALL=en_US.UTF-8"]
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "https://minio.example.com"
      AccessKey = "ACCESSKEYACCESSKEYAC"
      SecretKey = "secretkeysecretkeysecretkeysecretkey"
      BucketName = "gitlab-runner-cache"
      BucketLocation = "us-east-1"
      Insecure = false
  [runners.docker]
    tls_verify = true
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
