# =========================================
# Gitlab Runner
#
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

volumes:
  gitlab-runner-config:
    name: gitlab-runner-config
    external: true

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    environment:
      - TZ=UTC
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
