# =========================================
# Adminer
#
# Requires:
# - Docker Compose 1.27.0+
# - Docker Engine 19.03.0+
# =========================================

networks:
  database-net:
    name: database-net
    external: true
  proxy-net:
    name: reverse-proxy
    external: true

services:
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_PLUGINS=dump-zip
      - ADMINER_DEFAULT_SERVER=mysql
    # labels:
    #   # Labels for Traefik proxy
    #   - traefik.enable=true
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.routers.adminer.entrypoints=websecure
    #   - traefik.http.routers.adminer.rule=Host(`dba.example.com`)
    #   - traefik.http.routers.adminer.middlewares=internal-ips,admin-auth
    #   - traefik.http.routers.adminer.service=adminer
    #   - traefik.http.routers.adminer.priority=10
    #   - traefik.http.services.adminer.loadbalancer.server.port=8080
    networks:
      - database-net
      - proxy-net
    # ports:
    #   - 8080:8080
    restart: unless-stopped
