# =========================================
# Adminer
# Verion latest
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

networks:
  # Network for connectting to databases
  database-net:
    name: database-net
    external: true
  # Network for connectting to proxy server
  proxy-net:
    name: reverse-proxy
    external: true

services:
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_PLUGINS=dump-zip
      - ADMINER_DEFAULT_SERVER=mysql
    # # Labels for Traefik proxy
    # labels:
    #   - traefik.enable=true
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.routers.adminer.entrypoints=websecure
    #   - traefik.http.routers.adminer.rule=Host(`dba.example.com`)
    #   - traefik.http.routers.adminer.middlewares=internal-ips,admin-auth
    #   - traefik.http.routers.adminer.service=adminer
    #   - traefik.http.routers.adminer.tls=true
    #   - traefik.http.routers.adminer.tls.certresolver=le
    #   - traefik.http.routers.adminer.priority=10
    #   - traefik.http.services.adminer.loadbalancer.server.port=8080
    networks:
      - database-net
      - proxy-net
    # # Ports mapping
    # ports:
    #   - 8080:8080
    restart: unless-stopped
