# =========================================
# MySQL 8.0.x
# https://hub.docker.com/_/mysql
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  mysql-net:
    name: database-net
    external: true

volumes:
  mysql-vol:
    name: mysql-vol
    external: true

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - mysql-net
    # ports:
    #   - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysqladmin ping -u root -h localhost -s"]
      start_period: 20s
      retries: 3
      timeout: 3s
      interval: 10s
