# =========================================
# Timescaledb
#
# Note: Timescaledb build base PostgreSQL image, so that it is using like PostgreSQL docker image
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

networks:
  database-net:
    name: database-net
    external: true

secrets:
  postgres-password:
    external: true
    name: postgres-password

volumes:
  postgres-vol:
    name: postgres-vol
    external: true

services:
  postgres:
    image: timescale/timescaledb:latest-pg13
    # image: timescale/timescaledb-postgis:latest-pg13
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    networks:
      - database-net
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    secrets:
      - postgres-password
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    healthcheck:
      test: CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10
