## DYNAMIC CONFIG

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile:  /etc/traefik/certs/key.pem
# when troubleshooting certs, enable this so traefik doesn't use
# its own self-signed. By default if it can't find a matching
# cert, it'll just create its own which will cause cert warnings
# in browser and can be confusing to troubleshoot
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.pem
        keyFile: /etc/traefik/certs/key.pem

http:
  middlewares:
    force-https:
      redirectScheme:
        scheme: https
        port: 443
        permanent: true
