# =========================================
# PostgreSQL
#
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

networks:
  postgres-net:
    name: database-net
    external: true

secrets:
  postgres-dbname:
    external: true
    name: postgres-dbname
  postgres-username:
    external: true
    name: postgres-username
  postgres-password:
    external: true
    name: postgres-password

volumes:
  postgres-vol:
    name: postgres-vol
    external: true

services:
  postgres:
    image: postgres:alpine
    environment:
      # - POSTGRES_INITDB_ARGS=
      - POSTGRES_DB_FILE=/run/secrets/postgres-dbname
      - POSTGRES_USER_FILE=/run/secrets/postgres-username
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    networks:
      - postgres-net
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    secrets:
      - postgres-dbname
      - postgres-username
      - postgres-password
    stop_signal: SIGINT
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    healthcheck:
      test: CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10
