# =========================================
# Dgraph
#
# This Docker Compose file can be used to quickly bootup a simple stack with Dgraph Zero and Alpha in different
# Docker containers.
#
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================
version: "3.5"

networks:
  dgraph-net:
    name: database-net
    external: true

volumes:
  dgraph-vol:
    name: dgraph-vol
    external: true

services:
  zero:
    image: dgraph/dgraph:latest
    command: dgraph zero --my=zero:5080
    networks:
      - dgraph-net
    # ports:
    #   - 5080:5080
    #   - 6080:6080
    restart: unless-stopped
    volumes:
      - dgraph-vol:/dgraph

  alpha:
    image: dgraph/dgraph:latest
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080
    networks:
      - dgraph-net
    # ports:
    #   - 8080:8080
    #   - 9080:9080
    restart: unless-stopped
    volumes:
      - dgraph-vol:/dgraph
