# =========================================
# Dgraph
#
# This Docker Compose file can be used to quickly bootup a standalone stack with Dgraph Zero and Alpha in same
# Docker container.
#
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================
version: "3.5"

networks:
  dgraph-net:
    name: database-net
    external: true

volumes:
  dgraph-vol:
    name: dgraph-vol
    external: true

services:
  dgraph:
    image: dgraph/standalone:v21.03.1
    networks:
      - dgraph-net
    # ports:
    #   - 5080:5080
    #   - 6080:6080
    #   - 8080:8080
    #   - 9080:9080
    restart: unless-stopped
    volumes:
      - dgraph-vol:/dgraph
