# =========================================
# MeiliSearch
#
# https://docs.meilisearch.com/learn/getting_started/installation.html
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  meilisearch-net:
    external: true
    name: meilisearch-net

volumes:
  meilisearch-vol:
    external: true
    name: meilisearch-vol

services:
  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_ENV=production
      - MEILI_DB_PATH=/data.ms
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_SENTRY=true
    networks:
      - meilisearch-net
    # ports:
    #   - 7700:7700
    restart: unless-stopped
    volumes:
      - meilisearch-vol:/data.ms
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 20s
      test: wget --no-verbose --spider http://`hostname -i`:7700/health
      timeout: 5s
