# =========================================
# Redis
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  redis-net:
    name: redis-net
    external: true

volumes:
  redis-vol:
    name: redis-vol
    external: true

services:
  redis:
    image: redis:6-alpine
    networks:
      - redis-net
    # ports:
    #   - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      retries: 3
      timeout: 5s
      interval: 10s
