# =========================================
# Redis
# Verion 6-alpine
# Requires:
# - Docker Engine 17.12.0+
# - Docker Compose 1.18.0+
# =========================================

version: "3.5"

networks:
  redis-net:
    name: redis-net
    external: true

volumes:
  redis-vol:
    name: redis-vol
    external: true

services:
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    networks:
      - redis-net
    # ports:
    #   - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    healthcheck:
      interval: 3s
      retries: 5
      start_period: 15s
      test: PING=$$(redis-cli -h `hostname -i` -p 6379 ping) && [ "$$PING" == "PONG" ]
      timeout: 3s
